---

name: try docker push image

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker build -t slassalle/mavache:1 .
          docker login -u slassalle -p $DOCKERHUB_TOKEN
          docker push slassalle/mavache:1
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
